### ISSUE TITLE
Selecionar um caso de uso para ser implementado na SPRINT 1. Escrever os fluxos alternativos do caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [Joycesg/ppads-projeto-05k-2018s2#2]

**Comment by tmsasaki** [comment]
Escrever fluxos alternativos considerando o preenchimento ou não de informações opcionais.

**Comment by brbelarmino1** [comment]
Caso de uso selecionado: Publicar Serviço 

"Fluxo Alternativo - Dados incorretos" no documento caso-de-uso.md.
