### ISSUE TITLE
Selecionar um caso de uso para implementar na SPRINT 2. Escrever os fluxos alternativos deste caso de uso. Escrever um plano de testes (criar um arquivo plano-de-testes.md na pasta docs).

### ISSUE THREAD

**Issue by tmsasaki** [Joycesg/ppads-projeto-05k-2018s2#6]

**Comment by brbelarmino1** [comment]
Casos de uso selecionado:  Solicitar Orçamento 
Casos de uso - fluxo principal: Ok 
Casos de uso - fluxo fluxos alternativos: Ok 
Casos de teste - caixa preta: Ok

**Comment by tmsasaki** [comment]
No documento de casos de uso:

* Poderia haver duas formas de solicitação de orçamento: para um prestador específico (o cliente seleciona o nome do prestador) ou para todos os prestadores de uma determinada especialidade (neste caso, vários prestadores poderiam enviar um orçamento em resposta à solicitação do cliente).

**Comment by tmsasaki** [comment]
Alterar o plano de testes acrescentando o passo de acessar o banco de dados para verificar se o registro com os dados foram inseridos (detalhar quais informações deverão estar nos campos do registro).

**Comment by tmsasaki** [comment]
Escrever os casos de teste correspondentes a todos os casos de uso.

**Comment by tmsasaki** [comment]
Vou fechar esta ISSUE e criar um novo referente à ATUALIZAÇÃO DO PLANO DE TESTES.
