### ISSUE TITLE
Elaborar um DIAGRAMA DE IMPLANTAÇÃO (DEPLOYMENT DIAGRAM) da solução.

### ISSUE THREAD

**Issue by tmsasaki** [Joycesg/ppads-projeto-05k-2018s2#9]
Dica: procurar por DEPLOYMENT DIAGRAM UML para ver alguns exemplos.

**Comment by tmsasaki** [comment]
Falta elaborar o diagrama.

**Comment by brbelarmino1** [comment]
Feito. Disponível no repositório do GitHub na pasta Docs.
